//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zayavkiremont
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestID { get; set; }
        public string RequestNumber { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> FaultTypeID { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ExecutorID { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Executors Executors { get; set; }
        public virtual FaultTypes FaultTypes { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
